### PR TITLE
fix Ops signature; move matrixOps out of Ops group

### LINKED ISSUE #321: `Ops.S7_object`  containing `%*%`
Related to #320, I was exploring and found that indeed, dispatch for arithmetic happens with group method for `Ops` :
```
S7:::Ops.S7_object
function (e1, e2) 
{
    base_ops[[.Generic]](e1, e2)
}
<bytecode: 0x80a7f08>
<environment: namespace:S7>
```
and indeed, as mentioned in #320   the `base_ops` involved here are somewhat not initialized (anymore ?) and just empty.
**HOWEVER**  there is more:   The S7 `base_ops`  do contain `%*%`  but really really should NOT.

It seems clear this is currently explicitly "desired" --- probably because we don't want `S7` to depend on R 4.3.0 yet, and hence keep the code simple enough...
     https://github.com/RConsortium/OOP-WG/blame/main/R/zzz.R#L105
but it is really "wrong" and in contrast with base R's documentation of  group generics (`?groupGenerics`) which explains that `"matrixOps"` is a separate group generic.

### PR DESCRIPTION
**Pull request by t-kalinowski**
This PR: 

1. Changes the S7-internal Ops group generics signature from `x, y` to `e1, e2`, matching base R.
2. Moves matrixOps generics out of the Ops dispatch code path. `matrixOps.S7_object` is no longer an alias of `Ops.S7_object`, and `Ops.S7_object` no longer dispatches `%*%`.

closes #321

### CODE REVIEW

**Comment by t-kalinowski** [comment]
Looks like one small patch in the tools package will be necessary before S7 can pass R CMD check with the new, updated (and correct) matrixOps signature. https://github.com/r-devel/r-svn/pull/134/files The change is confined to the static-analysis checks only - both `Ops` and `matrixOps` groups match arguments positionally only when evaluated normally, with argument names ignored.

**Review by hadley — APPROVED** [review]

**Comment by hadley** [comment]
Why are we seeing build failures on the latest release?

**Comment by t-kalinowski** [comment]
The {tools} package was enforcing the wrong signature for matrixOps methods. This is fixed and will be part of R 4.4.0 (afaik)( https://github.com/r-devel/r-svn/pull/134, https://github.com/r-devel/r-svn/commit/b0abc0edbe4ae1a61ee95bb1f049014b8738a2dd). 

To avoid the R CMD check warning with the current release and older versions of R, I've added a special case that will define `matrixOps.S7_object` with the "wrong" signature for R versions prior to 4.4.0.

**Comment by hadley** [comment]
Perfect, thanks!

**Pull request merged**
